name = "go2asia-referral-service"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "connect.go2asia.space/*", zone_name = "go2asia.space" }
]

[env.staging]
routes = [
  { pattern = "connect-staging.go2asia.space/*", zone_name = "go2asia.space" }
]

[vars]
ENVIRONMENT = "development"

