name = "go2asia-api-gateway"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "api.go2asia.space/*", zone_name = "go2asia.space" }
]

[env.staging]
name = "go2asia-api-gateway-staging"
routes = [
  { pattern = "api-staging.go2asia.space/*", zone_name = "go2asia.space" }
]

[vars]
ENVIRONMENT = "development"

